// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOjst0AT8qmKeBTwekmHrnkitcX4xrZR8',
    appId: '1:436537772120:web:9abe10c0f382297ec8e22d',
    messagingSenderId: '436537772120',
    projectId: 'rolli-polli',
    authDomain: 'rolli-polli.firebaseapp.com',
    storageBucket: 'rolli-polli.appspot.com',
    measurementId: 'G-RF5GS138V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcy0Tx4nZ91SUn_ZfphfxA7SpcSrMH6Z4',
    appId: '1:436537772120:android:a4b3363a9d1181b5c8e22d',
    messagingSenderId: '436537772120',
    projectId: 'rolli-polli',
    storageBucket: 'rolli-polli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATcv1NOGhd9t1KCZm5XHAV2IV941QAFcI',
    appId: '1:436537772120:ios:9ba10ea178a42b7cc8e22d',
    messagingSenderId: '436537772120',
    projectId: 'rolli-polli',
    storageBucket: 'rolli-polli.appspot.com',
    iosClientId:
        '436537772120-um94tmljr3ha1m12a5bkhssqagc71e35.apps.googleusercontent.com',
    iosBundleId: 'com.NicholasEastmond.polls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATcv1NOGhd9t1KCZm5XHAV2IV941QAFcI',
    appId: '1:436537772120:ios:74dab5cddb4732f4c8e22d',
    messagingSenderId: '436537772120',
    projectId: 'rolli-polli',
    storageBucket: 'rolli-polli.appspot.com',
    iosClientId:
        '436537772120-87fpvvp4uruivuvvii2qihj2giop6qo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.polls',
  );
}
